name: Run Salesforce DataLoader with Multiple CSV Files

on:
  pull_request:
    branches:
      - main

jobs:
  run-dataloader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'


      # Checkout the tooling-branch to get the pre-installed libraries
      - name: Checkout Tooling Branch (for Groovy and SFDX CLI)
        run: git checkout tooling-branch -- libs/

      # Set up Groovy from the libs folder
      - name: Set Up Groovy
        run: |
          export GROOVY_HOME=$PWD/libs/groovy
          export PATH=$GROOVY_HOME/bin:$PATH
          groovy --version  # Check Groovy version

     # - name: Install Groovy
      #  run: sudo apt-get install -y groovy

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth_url.txt
          sfdx auth:sfdxurl:store -f sfdxAuthUrl.txt -s

      - name: Test groovy Script
        env:
          SF_SANDBOX_ALIAS: ${{ secrets.SF_SANDBOX_ALIAS }}
        run: groovy test.groovy
        
      - name: Access config file
        run: cat file/Account.sdl

      - name: Run DataLoader Script
        env:
          SF_SANDBOX_ALIAS: ${{ secrets.SF_SANDBOX_ALIAS }}
        run: groovy dataload.groovy
