name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
      - Dev

jobs:
  salesforce-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Install Salesforce CLI
        run: |
          #npm install sfdx-cli --global
          npm install @salesforce/cli@latest -g
          echo 'y' | sfdx plugins:install sfdx-git-delta

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth_url.txt
          sfdx auth:sfdxurl:store -f sfdxAuthUrl.txt -s

      - name: Build project
        run: |
          mkdir -p output
          echo "Build output" > output/build.txt

      - name: Generate Delta Package
        run: |
          sfdx sgd:source:delta --to HEAD --from HEAD^ --output output  --generate-delta

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output/

      - name: Validate Deployment
        run: |
          sf project deploy validate --manifest output/package/package.xml --test-level RunLocalTests --json > validation_log.txt 2>&1 || exit 1

      - name: Capture validation log
        id: capture-log
        run: |
          # Extract a part of the log to display in the comment (for brevity)
          tail -n 30 validation_log.txt > truncated_log.txt

      - name: Post Salesforce validation success comment
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const validationLog = fs.readFileSync('truncated_log.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              ### ✅ Salesforce Validation Successful

              🚀 **Validation passed successfully!**

              All metadata changes have been validated against Salesforce.

              ---

              **Validation Log (last 30 lines)**:
              \`\`\`
              ${validationLog}
              \`\`\`

              ---

              **Validation Summary**:
              - Branch: \`${context.payload.pull_request.head.ref}\`
              - PR: #${context.payload.pull_request.number}
              - Author: ${context.payload.pull_request.user.login}

              _No issues detected. You're good to go!_
              `
            });

      - name: Capture validation failure log
        id: capture-log-f
        if: failure()
        run: |
          # Extract a part of the log to display in the comment (for brevity)
          tail -n 30 validation_log.txt > truncated_log.txt


      - name: Post Salesforce validation failure comment
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('truncated_log.txt')) {
              const validationLog = fs.readFileSync('truncated_log.txt', 'utf8');
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `
                ### ❌ Salesforce Validation Failed

                😞 **Validation encountered issues!**

                There were errors during the validation process. Please review the following Salesforce validation logs:

                ---

                **Validation Log (last 30 lines)**:
                \`\`\`
                ${validationLog}
                \`\`\`

                ---

                **Validation Summary**:
                - Branch: \`${context.payload.pull_request.head.ref}\`
                - PR: #${context.payload.pull_request.number}
                - Author: ${context.payload.pull_request.user.login}

                _Please check the logs and fix the errors before retrying._
                `
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `
                ### ❌ Salesforce Validation Failed

                😞 **Validation encountered issues!**

                However, no log was captured. Please check the action run for more details.
                `
              });
            }
