name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  salesforce-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth_url.txt
          sfdx auth:sfdxurl:store -f sfdxAuthUrl.txt -s

      - name: Generate Delta Package
        run: |
          sfdx sgd:source:delta --to HEAD --from HEAD^ --output $(Build.ArtifactStagingDirectory)  --generate-delta

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output/

      - name: Validate Deployment
        run: |
          sf project deploy validate --manifest output/package/package.xml --test-level RunLocalTests
