name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  salesforce-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth_url.txt
          sfdx auth:sfdxurl:store -f sfdxAuthUrl.txt -s

      - name: Generate Delta Package
        run: |
          git diff --name-only origin/main...HEAD > delta.txt
          cat delta.txt

      - name: Convert Source to Metadata API Format
        run: |
          sfdx force:source:convert -r force-app -d output_dir -p $(cat delta.txt)

      - name: Validate Deployment
        run: |
          sfdx force:mdapi:deploy -d output_dir -u MyOrg --checkonly --testlevel RunLocalTests
