name: Data Bulk Operation new

on:
  workflow_dispatch:
    inputs:
      csv_files:
        description: 'CSV file names (comma-separated)'
        required: true
        default: 'Account.csv'
      operation:
        description: 'Type of operation (insert/upsert/delete)'
        required: true
        default: 'upsert'

jobs:
  bulk-operation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java (required for Groovy)
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install Groovy
        run: sudo apt-get install -y groovy

      - name: Set up Salesforce CLI
        run: |
          sudo npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} > auth_url.txt
          sfdx auth:sfdxurl:store -f sfdxAuthUrl.txt -s
        #sf org login sfdx-url -f sfdxAuthUrl.txt --set-default

      - name: Run Bulk Operation Script
        run: |
          groovy bulkOperations.groovy "${{ github.event.inputs.csv_files }}" "${{ github.event.inputs.operation }}"
